# conda env update --file environment.yml
name: null
channels:
    - conda-forge
dependencies:
    - hyperopt
    - matplotlib
    - numpy
    - pandas
    - pip
    - pyyaml
    - scikit-optimize
    - scipy
    - scikit-learn
    - seaborn
    - setproctitle
    - pip:
        - ray
        - environment_kernels
        

